_BASE_: "base.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  SEM_SEG_HEAD:
    NUM_CLASSES: 21
  DILATED_RESNET:
    DEPTH: 101
DATASETS:
  TRAIN: ("voc_2012_trainval",)
  TEST: ("voc_2012_test",)
SOLVER:
  IMS_PER_BATCH: 16
OUTPUT_DIR: "./output/r101/voc"
