_BASE_: "base.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  SEM_SEG_HEAD:
    NUM_CLASSES: 171
  DILATED_RESNET:
    DEPTH: 50
DATASETS:
  TRAIN: ("coco_2017_train_panoptic_stuffonly",)
  TEST: ("coco_2017_val_panoptic_stuffonly",)
SOLVER:
  IMS_PER_BATCH: 16
OUTPUT_DIR: "./output/r50/coco"
